name: basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip cython wheel
          pip install -r requirements.txt

      # Step 4: Run pylint
      - name: Run black
        run: |
          find . -iname "*.py" -not -path "./tests/*" | xargs -n1 -I {} pylint --output-format=colorized {} || true

      # Step 5: Run pytest
      - name: Run pytest
        run: |
          PYTHONDONTWRITEBYTECODE=1 pytest -v --color=yes
