name: basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-run-pytest:
    runs-on: ubuntu-latest

    steps:
      # First step: checkout the repository
      - uses: actions/checkout@v3

      # Second step: install Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Third step: install Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip cython wheel
          pip install -r requirements.txt

      # Fourth step: run tests with Pytest
      - name: Run tests
        run: make
